### ISSUE TITLE
Having some problem with the Boolfuck kata with Rust

### ISSUE THREAD

**Issue by madprops** [DonaldKellett/Codewars-Authored-Kata#1]
I implemented it, tested with the first 2 cases and it worked.
I pasted it to check all sample tests, but it outputs:

```
error[E0425]: cannot find function `boolfuck` in this scope
  --> src/lib.rs:65:20
   |
65 |         assert_eq!
```

And below.

```
   |                    ^^^^^^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
   |
1  | use boolfuck;
   |
```

My function's header is:

```
fn boolfuck(code: &str, input: Vec<u8>) -> Vec<u8>
```

I tried using the boolfuck module, but it errored, or I don't know how to use it.
I don't know what to do.
I post this here because I can't see a Discuss button in the kata.

**Comment by DonaldKellett** [comment]
> I post this here because I can't see a Discuss button in the kata.

The Discourse of said Kata is available at https://www.codewars.com/kata/5861487fdb20cff3ab000030/discuss
